# Generated by Django 4.2.4 on 2023-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_cands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cands',
            name='age',
        ),
        migrations.AlterField(
            model_name='cands',
            name='cv',
            field=models.FileField(upload_to='cvs/% Y/% m/% d/'),
        ),
    ]
