# Generated by Django 4.2.4 on 2023-08-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_cands'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('candID', models.AutoField(primary_key=True, serialize=False)),
                ('cand_status', models.CharField(choices=[('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('on stack', 'On Stack')], default='reviewed', max_length=10)),
                ('military_status', models.CharField(choices=[('completed', 'Completed'), ('not completed', 'Not Completed'), ('exempted', 'Exempted')], default='not completed', max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('cv', models.FileField(upload_to='cvs/%Y-%m-%d/')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='candidate_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('candID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.candidate')),
            ],
            options={
                'db_table': 'candidate_account',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('depID', models.AutoField(primary_key=True, serialize=False)),
                ('depName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='human_resources',
            fields=[
                ('HR_code', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'human_resources',
            },
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('jobID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('HR_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.human_resources')),
                ('depID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.DeleteModel(
            name='candAccount',
        ),
        migrations.DeleteModel(
            name='cands',
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.job'),
        ),
    ]
