# Generated by Django 4.2.4 on 2023-08-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_candidate_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
