# Generated by Django 4.2.4 on 2023-08-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_job_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='counter',
            new_name='applicants_count',
        ),
    ]
