# Generated by Django 4.2.4 on 2023-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_counter_job_applicants_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='background_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage', models.URLField(max_length=255)),
                ('jobs', models.URLField(max_length=255)),
                ('application', models.URLField(max_length=255)),
                ('thank_you', models.URLField(max_length=255)),
                ('logout', models.URLField(max_length=255)),
                ('login', models.URLField(max_length=255)),
                ('account', models.URLField(max_length=255)),
            ],
            options={
                'db_table': 'background_images',
            },
        ),
    ]
