# Generated by Django 4.2.4 on 2023-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_background_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background_images',
            name='account',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='background_images',
            name='application',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='background_images',
            name='homepage',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='background_images',
            name='jobs',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='background_images',
            name='login',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='background_images',
            name='logout',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='background_images',
            name='thank_you',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
