# Generated by Django 4.2.4 on 2023-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_background_images_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='depName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior')], default='Entry', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria')], default='Cairo', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_arrangement',
            field=models.CharField(choices=[('Office', 'Office'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Office', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='applicants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
