# Generated by Django 4.2.4 on 2023-08-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_job_depname_job_level_job_location_job_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
