<<<<<<<< HEAD:authentication/migrations/0015_merge_20230824_0933.py
# Generated by Django 4.2.4 on 2023-08-24 06:33
========
# Generated by Django 4.2.4 on 2023-08-23 13:00
>>>>>>>> 8280782dd91503df848396b99ada2cd4eead3331:authentication/migrations/0015_merge_20230823_1600.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_candidate_note'),
        ('authentication', '0014_job_date_posted_job_is_active'),
    ]

    operations = [
    ]
