# Generated by Django 4.2.4 on 2023-08-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_candidate_note'),
        ('authentication', '0014_job_date_posted_job_is_active'),
    ]

    operations = [
    ]
