# Generated by Django 4.2.4 on 2023-08-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_merge_20230827_1127'),
    ]

    operations = [
        
    ]
