# Generated by Django 4.2.4 on 2023-08-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_merge_20230826_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.TextField()),
                ('Major', models.TextField()),
                ('Education', models.TextField()),
                ('LinkedIn', models.URLField()),
                ('Work_Experience', models.TextField()),
                ('SoftSkill', models.TextField()),
                ('TechSkill', models.TextField()),
                ('AddNote', models.TextField()),
                ('pdf_file', models.URLField()),
            ],
            options={
                'db_table': 'CVGen',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='To_Candidate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
