# Generated by Django 4.2.4 on 2023-08-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_merge_20230823_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='To_Candidate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
