# Generated by Django 4.2.4 on 2023-08-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_merge_20230822_0912'),
        ('authentication', '0015_merge_20230822_0914'),
    ]

    operations = [
    ]
