# Generated by Django 4.2.4 on 2023-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_candcv_candidate_to_candidate_candidate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='none', max_length=6),
        ),
    ]
