# Generated by Django 4.2.4 on 2023-08-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_candidate_to_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='jobTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
