# Generated by Django 4.2.4 on 2023-08-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_candcv_candidate_to_candidate_candidate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.TextField()),
                ('Major', models.TextField()),
                ('Education', models.TextField()),
                ('LinkedIn', models.URLField()),
                ('Work_Experience', models.TextField()),
                ('SoftSkill', models.TextField()),
                ('TechSkill', models.TextField()),
                ('AddNote', models.TextField()),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        
    ]
