# Generated by Django 4.2.4 on 2023-08-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_resume_candidate_to_candidate_candidate_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='depID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
        ),
    ]
