# Generated by Django 4.2.4 on 2023-08-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_candidate_jobtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='jobTitle',
        ),
    ]
