# Generated by Django 4.2.4 on 2023-08-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_resume_candidate_to_candidate_candidate_depid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='jobs_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
