# Generated by Django 4.2.4 on 2023-09-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_cv_candidate_to_candidate_candidate_title'),
        ('authentication', '0019_resume_candidate_to_candidate_candidate_title_and_more'),
    ]

    operations = [
    ]
