# Generated by Django 4.2.4 on 2023-08-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_merge_20230824_0933'),
        ('authentication', '0019_candidate_title'),
    ]

    operations = [
    ]
