# Generated by Django 4.2.4 on 2023-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ExtraCurricular',
            field=models.TextField(default='none'),
        ),
    ]
